<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ8CNsrg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ8CNsrg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQ8CNsrg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQ8CNsrg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQ8CNsrg\App_KernelDevDebugContainer([
    'container.build_hash' => 'Q8CNsrg',
    'container.build_id' => '97f7f6ec',
    'container.build_time' => 1578598860,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ8CNsrg');
